# Generated by Django 2.2.4 on 2019-08-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('bar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bars.Bar')),
            ],
            bases=('bars.bar',),
        ),
    ]
