# Generated by Django 2.2.4 on 2019-08-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='owner_bar_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='owner_bar_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
