# Generated by Django 2.2.4 on 2019-08-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
        ('users', '0003_auto_20190807_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bars.Bar'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bars.Bar'),
        ),
        migrations.AddField(
            model_name='user',
            name='third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bars.Bar'),
        ),
    ]
