# Generated by Django 2.2.4 on 2019-08-08 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
        ('users', '0004_auto_20190808_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('bar_heart', models.ForeignKey(default='알수없음', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bar_heart', to='bars.Bar')),
                ('user_heart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_heart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
