# Generated by Django 2.2.4 on 2019-08-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_bar_hours'),
        ('users', '0005_heart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fifth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bars.Bar'),
        ),
        migrations.AddField(
            model_name='user',
            name='fourth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bars.Bar'),
        ),
    ]
