# Generated by Django 2.2.4 on 2019-08-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('represent_image', models.ImageField(blank=True, null=True, upload_to='bars')),
                ('first_image', models.ImageField(blank=True, null=True, upload_to='bars')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='bars')),
                ('summary', models.CharField(max_length=300, null=True)),
                ('text', models.TextField(max_length=200)),
                ('location_url', models.TextField(blank=True, max_length=200, null=True)),
                ('keyword', models.CharField(max_length=80, null=True)),
                ('menu', models.CharField(blank=True, max_length=150, null=True)),
                ('bar_phone', models.IntegerField(null=True)),
                ('lat', models.FloatField(max_length=40)),
                ('lng', models.FloatField(max_length=40)),
                ('mood1', models.BooleanField(default=False)),
                ('mood2', models.BooleanField(default=False)),
                ('mood3', models.BooleanField(default=False)),
                ('mood4', models.BooleanField(default=False)),
                ('mood5', models.BooleanField(default=False)),
                ('mood6', models.BooleanField(default=False)),
                ('mood7', models.BooleanField(default=False)),
                ('mood8', models.BooleanField(default=False)),
                ('chicken', models.BooleanField(default=False)),
                ('jokbal', models.BooleanField(default=False)),
                ('ijakaya', models.BooleanField(default=False)),
                ('gogi', models.BooleanField(default=False)),
                ('joongkuk', models.BooleanField(default=False)),
                ('whui', models.BooleanField(default=False)),
                ('pojang', models.BooleanField(default=False)),
                ('junjip', models.BooleanField(default=False)),
                ('pizza', models.BooleanField(default=False)),
                ('hopjip', models.BooleanField(default=False)),
                ('gookbab', models.BooleanField(default=False)),
                ('yang', models.BooleanField(default=False)),
                ('hansik', models.BooleanField(default=False)),
                ('inwon_xsmall', models.BooleanField(default=False)),
                ('inwon_small', models.BooleanField(default=False)),
                ('inwon_medium', models.BooleanField(default=False)),
                ('inwon_large', models.BooleanField(default=False)),
                ('inwon_xlarge', models.BooleanField(default=False)),
                ('silwoi', models.BooleanField(default=False)),
                ('silne', models.BooleanField(default=False)),
                ('gongyong', models.BooleanField(default=False)),
                ('bulli', models.BooleanField(default=False)),
                ('nomatter', models.BooleanField(default=False)),
            ],
        ),
    ]
