# Generated by Django 2.2.4 on 2019-08-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='hours',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
